server:
  port: 8081

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/users_db}
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

app:
  jwt-secret: ${JWT_SECRET}
  jwt-expiration-ms: ${JWT_EXPIRATION_MS:86400000}
  avatar-upload-dir: ${AVATAR_UPLOAD_DIR:uploads/avatars}

management:
  endpoints:
    web:
      exposure:
        include: health,info
