sonar.projectKey=safe-zone-ecommerce
sonar.projectName=Safe Zone E-Commerce Microservices
sonar.projectVersion=1.0

sonar.sources=backend/discovery-service/src/main/java,backend/gateway-service/src/main/java,backend/user-service/src/main/java,backend/product-service/src/main/java,backend/media-service/src/main/java,frontend/src
sonar.tests=backend/discovery-service/src/test/java,backend/gateway-service/src/test/java,backend/user-service/src/test/java,backend/product-service/src/test/java,backend/media-service/src/test/java
sonar.test.inclusions=backend/**/src/test/**/*

sonar.java.binaries=backend/**/target/classes
sonar.java.test.binaries=backend/**/target/test-classes
sonar.coverage.jacoco.xmlReportPaths=backend/**/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/buy-01-frontend/lcov.info
sonar.typescript.tsconfigPath=frontend/tsconfig.json

sonar.exclusions=**/target/**,**/node_modules/**,**/dist/**,**/.angular/**,**/coverage/**,**/test-results/**,**/*.class,**/*.jar,frontend/src/**/*.spec.ts,uploads/**
sonar.coverage.exclusions=**/*Application.java,**/dto.java,frontend/src/main.ts,frontend/src/environments/**
sonar.sourceEncoding=UTF-8
